controller_joint_names: ['', 
'L1_1J', 'L1_2J', 'L1_3J', 
'R1_1J', 'R1_2J', 'R1_3J', 
'L2_1J', 'L2_2J', 'L2_3J', 
'R2_1J', 'R2_2J', 'R2_3J', 
'L3_1J', 'L3_2J', 'L3_3J', 
'R3_1J', 'R3_2J', 'R3_3J', ]
