(cl:defpackage traversability_msgs-srv
  (:use )
  (:export
   "CHECKFOOTPRINTPATH"
   "<CHECKFOOTPRINTPATH-REQUEST>"
   "CHECKFOOTPRINTPATH-REQUEST"
   "<CHECKFOOTPRINTPATH-RESPONSE>"
   "CHECKFOOTPRINTPATH-RESPONSE"
   "OVERWRITE"
   "<OVERWRITE-REQUEST>"
   "OVERWRITE-REQUEST"
   "<OVERWRITE-RESPONSE>"
   "OVERWRITE-RESPONSE"
  ))

