// Generated by gencpp from file traversability_msgs/CheckFootprintPathResponse.msg
// DO NOT EDIT!


#ifndef TRAVERSABILITY_MSGS_MESSAGE_CHECKFOOTPRINTPATHRESPONSE_H
#define TRAVERSABILITY_MSGS_MESSAGE_CHECKFOOTPRINTPATHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <traversability_msgs/TraversabilityResult.h>

namespace traversability_msgs
{
template <class ContainerAllocator>
struct CheckFootprintPathResponse_
{
  typedef CheckFootprintPathResponse_<ContainerAllocator> Type;

  CheckFootprintPathResponse_()
    : result()  {
    }
  CheckFootprintPathResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::traversability_msgs::TraversabilityResult_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::traversability_msgs::TraversabilityResult_<ContainerAllocator> >> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CheckFootprintPathResponse_

typedef ::traversability_msgs::CheckFootprintPathResponse_<std::allocator<void> > CheckFootprintPathResponse;

typedef boost::shared_ptr< ::traversability_msgs::CheckFootprintPathResponse > CheckFootprintPathResponsePtr;
typedef boost::shared_ptr< ::traversability_msgs::CheckFootprintPathResponse const> CheckFootprintPathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator1> & lhs, const ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator1> & lhs, const ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traversability_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "403c136f58a3e688827b9a267b872101";
  }

  static const char* value(const ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x403c136f58a3e688ULL;
  static const uint64_t static_value2 = 0x827b9a267b872101ULL;
};

template<class ContainerAllocator>
struct DataType< ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traversability_msgs/CheckFootprintPathResponse";
  }

  static const char* value(const ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# Traversability results\n"
"traversability_msgs/TraversabilityResult[] result\n"
"\n"
"================================================================================\n"
"MSG: traversability_msgs/TraversabilityResult\n"
"# If path is safe to traverse.\n"
"bool is_safe\n"
"\n"
"# Estimate of the traversability of the path.\n"
"# Ranges from 0 to 1 where 0 means not traversable and 1 highly traversable.\n"
"float64 traversability\n"
"\n"
"# Area of the footprint path.\n"
"float64 area\n"
;
  }

  static const char* value(const ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckFootprintPathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traversability_msgs::CheckFootprintPathResponse_<ContainerAllocator>& v)
  {
    s << indent << "result[]" << std::endl;
    for (size_t i = 0; i < v.result.size(); ++i)
    {
      s << indent << "  result[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::traversability_msgs::TraversabilityResult_<ContainerAllocator> >::stream(s, indent + "    ", v.result[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAVERSABILITY_MSGS_MESSAGE_CHECKFOOTPRINTPATHRESPONSE_H
