// Generated by gencpp from file traversability_msgs/CheckFootprintPath.msg
// DO NOT EDIT!


#ifndef TRAVERSABILITY_MSGS_MESSAGE_CHECKFOOTPRINTPATH_H
#define TRAVERSABILITY_MSGS_MESSAGE_CHECKFOOTPRINTPATH_H

#include <ros/service_traits.h>


#include <traversability_msgs/CheckFootprintPathRequest.h>
#include <traversability_msgs/CheckFootprintPathResponse.h>


namespace traversability_msgs
{

struct CheckFootprintPath
{

typedef CheckFootprintPathRequest Request;
typedef CheckFootprintPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckFootprintPath
} // namespace traversability_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traversability_msgs::CheckFootprintPath > {
  static const char* value()
  {
    return "c63bb28cc303394e26806233caf914bd";
  }

  static const char* value(const ::traversability_msgs::CheckFootprintPath&) { return value(); }
};

template<>
struct DataType< ::traversability_msgs::CheckFootprintPath > {
  static const char* value()
  {
    return "traversability_msgs/CheckFootprintPath";
  }

  static const char* value(const ::traversability_msgs::CheckFootprintPath&) { return value(); }
};


// service_traits::MD5Sum< ::traversability_msgs::CheckFootprintPathRequest> should match
// service_traits::MD5Sum< ::traversability_msgs::CheckFootprintPath >
template<>
struct MD5Sum< ::traversability_msgs::CheckFootprintPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traversability_msgs::CheckFootprintPath >::value();
  }
  static const char* value(const ::traversability_msgs::CheckFootprintPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traversability_msgs::CheckFootprintPathRequest> should match
// service_traits::DataType< ::traversability_msgs::CheckFootprintPath >
template<>
struct DataType< ::traversability_msgs::CheckFootprintPathRequest>
{
  static const char* value()
  {
    return DataType< ::traversability_msgs::CheckFootprintPath >::value();
  }
  static const char* value(const ::traversability_msgs::CheckFootprintPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traversability_msgs::CheckFootprintPathResponse> should match
// service_traits::MD5Sum< ::traversability_msgs::CheckFootprintPath >
template<>
struct MD5Sum< ::traversability_msgs::CheckFootprintPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traversability_msgs::CheckFootprintPath >::value();
  }
  static const char* value(const ::traversability_msgs::CheckFootprintPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traversability_msgs::CheckFootprintPathResponse> should match
// service_traits::DataType< ::traversability_msgs::CheckFootprintPath >
template<>
struct DataType< ::traversability_msgs::CheckFootprintPathResponse>
{
  static const char* value()
  {
    return DataType< ::traversability_msgs::CheckFootprintPath >::value();
  }
  static const char* value(const ::traversability_msgs::CheckFootprintPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAVERSABILITY_MSGS_MESSAGE_CHECKFOOTPRINTPATH_H
