// Generated by gencpp from file traversability_msgs/Overwrite.msg
// DO NOT EDIT!


#ifndef TRAVERSABILITY_MSGS_MESSAGE_OVERWRITE_H
#define TRAVERSABILITY_MSGS_MESSAGE_OVERWRITE_H

#include <ros/service_traits.h>


#include <traversability_msgs/OverwriteRequest.h>
#include <traversability_msgs/OverwriteResponse.h>


namespace traversability_msgs
{

struct Overwrite
{

typedef OverwriteRequest Request;
typedef OverwriteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Overwrite
} // namespace traversability_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traversability_msgs::Overwrite > {
  static const char* value()
  {
    return "8c1211af706069c994c06e00eb59ac9e";
  }

  static const char* value(const ::traversability_msgs::Overwrite&) { return value(); }
};

template<>
struct DataType< ::traversability_msgs::Overwrite > {
  static const char* value()
  {
    return "traversability_msgs/Overwrite";
  }

  static const char* value(const ::traversability_msgs::Overwrite&) { return value(); }
};


// service_traits::MD5Sum< ::traversability_msgs::OverwriteRequest> should match
// service_traits::MD5Sum< ::traversability_msgs::Overwrite >
template<>
struct MD5Sum< ::traversability_msgs::OverwriteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traversability_msgs::Overwrite >::value();
  }
  static const char* value(const ::traversability_msgs::OverwriteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traversability_msgs::OverwriteRequest> should match
// service_traits::DataType< ::traversability_msgs::Overwrite >
template<>
struct DataType< ::traversability_msgs::OverwriteRequest>
{
  static const char* value()
  {
    return DataType< ::traversability_msgs::Overwrite >::value();
  }
  static const char* value(const ::traversability_msgs::OverwriteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traversability_msgs::OverwriteResponse> should match
// service_traits::MD5Sum< ::traversability_msgs::Overwrite >
template<>
struct MD5Sum< ::traversability_msgs::OverwriteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traversability_msgs::Overwrite >::value();
  }
  static const char* value(const ::traversability_msgs::OverwriteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traversability_msgs::OverwriteResponse> should match
// service_traits::DataType< ::traversability_msgs::Overwrite >
template<>
struct DataType< ::traversability_msgs::OverwriteResponse>
{
  static const char* value()
  {
    return DataType< ::traversability_msgs::Overwrite >::value();
  }
  static const char* value(const ::traversability_msgs::OverwriteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAVERSABILITY_MSGS_MESSAGE_OVERWRITE_H
