// Generated by gencpp from file traversability_msgs/OverwriteRequest.msg
// DO NOT EDIT!


#ifndef TRAVERSABILITY_MSGS_MESSAGE_OVERWRITEREQUEST_H
#define TRAVERSABILITY_MSGS_MESSAGE_OVERWRITEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace traversability_msgs
{
template <class ContainerAllocator>
struct OverwriteRequest_
{
  typedef OverwriteRequest_<ContainerAllocator> Type;

  OverwriteRequest_()
    : enable(false)  {
    }
  OverwriteRequest_(const ContainerAllocator& _alloc)
    : enable(false)  {
  (void)_alloc;
    }



   typedef uint8_t _enable_type;
  _enable_type enable;





  typedef boost::shared_ptr< ::traversability_msgs::OverwriteRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traversability_msgs::OverwriteRequest_<ContainerAllocator> const> ConstPtr;

}; // struct OverwriteRequest_

typedef ::traversability_msgs::OverwriteRequest_<std::allocator<void> > OverwriteRequest;

typedef boost::shared_ptr< ::traversability_msgs::OverwriteRequest > OverwriteRequestPtr;
typedef boost::shared_ptr< ::traversability_msgs::OverwriteRequest const> OverwriteRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traversability_msgs::OverwriteRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traversability_msgs::OverwriteRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traversability_msgs::OverwriteRequest_<ContainerAllocator1> & lhs, const ::traversability_msgs::OverwriteRequest_<ContainerAllocator2> & rhs)
{
  return lhs.enable == rhs.enable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traversability_msgs::OverwriteRequest_<ContainerAllocator1> & lhs, const ::traversability_msgs::OverwriteRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traversability_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::traversability_msgs::OverwriteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traversability_msgs::OverwriteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traversability_msgs::OverwriteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traversability_msgs::OverwriteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traversability_msgs::OverwriteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traversability_msgs::OverwriteRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traversability_msgs::OverwriteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c1211af706069c994c06e00eb59ac9e";
  }

  static const char* value(const ::traversability_msgs::OverwriteRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c1211af706069c9ULL;
  static const uint64_t static_value2 = 0x94c06e00eb59ac9eULL;
};

template<class ContainerAllocator>
struct DataType< ::traversability_msgs::OverwriteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traversability_msgs/OverwriteRequest";
  }

  static const char* value(const ::traversability_msgs::OverwriteRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traversability_msgs::OverwriteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# True to enable, false for disable.\n"
"bool enable\n"
;
  }

  static const char* value(const ::traversability_msgs::OverwriteRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traversability_msgs::OverwriteRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OverwriteRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traversability_msgs::OverwriteRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traversability_msgs::OverwriteRequest_<ContainerAllocator>& v)
  {
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAVERSABILITY_MSGS_MESSAGE_OVERWRITEREQUEST_H
